Let's build a Multi-Layer Perceptron having

`1 Input Layer`, `3 Hidden Layer (16, 8, 4)`, `1 Output Layer`

In [43]:
import numpy as np
np.random.seed(42)

X=np.random.rand(1).reshape(-1,1)
Y_true=1

print(X.shape)
print(Y_true)

(1, 1)
1


weights, bias for `Input Layer` to `Hidden Layer 1`

In [52]:

np.random.seed(42)

w_input_hidden1=np.random.uniform(low=-1.0, high=1.0, size=(1,16))
# b_input_hidden1=np.random.uniform(low=-1.0, high=1.0, size=(1,16))
# initializing bias from zeros
b_input_hidden1=np.zeros((1,16))


print(w_input_hidden1.shape)
print(w_input_hidden1)
print(b_input_hidden1.shape)
print(b_input_hidden1)



(1, 16)
[[-0.25091976  0.90142861  0.46398788  0.19731697 -0.68796272 -0.68801096
  -0.88383278  0.73235229  0.20223002  0.41614516 -0.95883101  0.9398197
   0.66488528 -0.57532178 -0.63635007 -0.63319098]]
(1, 16)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


weights, bias for `Hidden Layer 1` to `Hidden Layer 2`

In [53]:

np.random.seed(42)

w_hidden1_hidden2=np.random.uniform(low=-1.0, high=1.0, size=(16,8))
# b_hidden1_hidden2=np.random.uniform(low=-1.0, high=1.0, size=(1,8))
b_hidden1_hidden2 = np.zeros((1, 8))

print(w_hidden1_hidden2.shape)
print(w_hidden1_hidden2)
print(b_hidden1_hidden2.shape)
print(b_hidden1_hidden2)

(16, 8)
[[-0.25091976  0.90142861  0.46398788  0.19731697 -0.68796272 -0.68801096
  -0.88383278  0.73235229]
 [ 0.20223002  0.41614516 -0.95883101  0.9398197   0.66488528 -0.57532178
  -0.63635007 -0.63319098]
 [-0.39151551  0.04951286 -0.13610996 -0.41754172  0.22370579 -0.72101228
  -0.4157107  -0.26727631]
 [-0.08786003  0.57035192 -0.60065244  0.02846888  0.18482914 -0.90709917
   0.2150897  -0.65895175]
 [-0.86989681  0.89777107  0.93126407  0.6167947  -0.39077246 -0.80465577
   0.36846605 -0.11969501]
 [-0.75592353 -0.00964618 -0.93122296  0.8186408  -0.48244004  0.32504457
  -0.37657785  0.04013604]
 [ 0.09342056 -0.63029109  0.93916926  0.55026565  0.87899788  0.7896547
   0.19579996  0.84374847]
 [-0.823015   -0.60803428 -0.90954542 -0.34933934 -0.22264542 -0.45730194
   0.65747502 -0.28649335]
 [-0.43813098  0.08539217 -0.71815155  0.60439396 -0.85089871  0.97377387
   0.54448954 -0.60256864]
 [-0.98895577  0.63092286  0.41371469  0.45801434  0.54254069 -0.8519107
  -0.283068

weights, bias for `Hidden Layer 2` to `Hidden Layer 3`

In [54]:

np.random.seed(42)

w_hidden2_hidden3 = np.random.uniform(low=-1.0, high=1.0, size=(8,4))
# b_hidden2_hidden3 = np.random.uniform(low=-1.0, high=1.0, size=(1, 4))
b_hidden2_hidden3 = np.zeros((1, 4))

print(w_hidden2_hidden3.shape)
print(w_hidden2_hidden3)
print(b_hidden2_hidden3.shape)
print(b_hidden2_hidden3)

(8, 4)
[[-0.25091976  0.90142861  0.46398788  0.19731697]
 [-0.68796272 -0.68801096 -0.88383278  0.73235229]
 [ 0.20223002  0.41614516 -0.95883101  0.9398197 ]
 [ 0.66488528 -0.57532178 -0.63635007 -0.63319098]
 [-0.39151551  0.04951286 -0.13610996 -0.41754172]
 [ 0.22370579 -0.72101228 -0.4157107  -0.26727631]
 [-0.08786003  0.57035192 -0.60065244  0.02846888]
 [ 0.18482914 -0.90709917  0.2150897  -0.65895175]]
(1, 4)
[[0. 0. 0. 0.]]


weights bias for `Hidden Layer 3` to `Output Layer`

In [55]:

np.random.seed(42)


w_hidden3_output=np.random.uniform(low=-1.0, high=1.0, size=(4,1))
# b_hidden3_output=np.random.uniform(low=-1.0, high=1.0, size=(1,1))
b_hidden3_output = np.zeros((1, 1))

print(w_hidden3_output.shape)
print(w_hidden3_output)
print(b_hidden3_output.shape)
print(b_hidden3_output)

(4, 1)
[[-0.25091976]
 [ 0.90142861]
 [ 0.46398788]
 [ 0.19731697]]
(1, 1)
[[0.]]


`Sigmoid Activation` function

In [49]:
def Sigmoid_Activation(z):
    return 1/(1+np.exp(-z))


Model Workflow

In [50]:


# from input -> hidden layer 1
z_input_hidden1=X@w_input_hidden1+b_input_hidden1 # (1,16)
a_input_hidden1=Sigmoid_Activation(z_input_hidden1) # (1,16)

# hidden layer 1 -> hidden layer 2
z_hidden1_hidden2=a_input_hidden1@w_hidden1_hidden2+b_hidden1_hidden2 # (1,8)
a_hidden1_hidden2=Sigmoid_Activation(z_hidden1_hidden2) # (1,8)

# hidden layer 2 -> hidden layer 3
z_hidden2_hidden3=a_hidden1_hidden2@w_hidden2_hidden3+b_hidden2_hidden3
a_hidden2_hidden3=Sigmoid_Activation(z_hidden2_hidden3) # (1,4)

# hidden layer 3 -> output layer
z_hidden3_output=a_hidden2_hidden3@w_hidden3_output+b_hidden3_output
Y_pred=Sigmoid_Activation(z_hidden3_output) # (1,1)



Training Loop

In [51]:
LR=0.01
epochs=100000

for epoch in range(epochs):

    # ============================== FORWARD PASS ===================================================
    # Input Layer -> Hidden Layer 1
    z_input_hidden1 = X@w_input_hidden1+b_input_hidden1  # (1,16)
    a_input_hidden1 = Sigmoid_Activation(z_input_hidden1)  # (1,16)

    # Hidden Layer 1 -> Hidden Layer 2
    z_hidden1_hidden2 = a_input_hidden1@w_hidden1_hidden2 + \
        b_hidden1_hidden2  # (1,8)
    a_hidden1_hidden2 = Sigmoid_Activation(z_hidden1_hidden2)  # (1,8)


    # Hidden Layer 2 -> Hidden Layer 3
    z_hidden2_hidden3 = a_hidden1_hidden2@w_hidden2_hidden3+b_hidden2_hidden3
    a_hidden2_hidden3 = Sigmoid_Activation(z_hidden2_hidden3)  # (1,4)


    # Hidden Layer 3 -> Output Layer
    z_hidden3_output = a_hidden2_hidden3@w_hidden3_output+b_hidden3_output
    Y_pred = Sigmoid_Activation(z_hidden3_output)  # (1,1)


    # LOSS FUNCTION
    L=0.5*(Y_pred - Y_true)**2

    # ====================================== BACKPROPAGATION =============================================
    # Output Layer -> Hidden Layer 3
    # ====================================== WEIGHTS GRADIENTS ===========================================
    # dL/dw_hidden3_output = dL/dY_pred * dY_pred/dz_hidden3_output * dz_hidden3_output/dw_hidden3_output

    dL_dY_pred = (Y_pred - Y_true) # (1,1)
    dY_pred_dz_hidden3_output = Y_pred * (1-Y_pred) # (1,1)
    dz_hidden3_output_dw_hidden3_output = a_hidden2_hidden3 # (1,4)

    # dL/dz_hidden3_output = dL/dY_pred * dY_pred/dz_hidden3_output
    dL_dz_hidden3_output = dL_dY_pred * dY_pred_dz_hidden3_output # (1,1)

    # dL/dw_hidden3_output = dL/dz_hidden3_output * dz_hidden3_output/dw_hidden3_output
    dL_dw_hidden3_output = dz_hidden3_output_dw_hidden3_output.T @ dL_dz_hidden3_output # (4,1)


    # ================================ BIAS GRADIENTS ==============================================
    # dL/db_hidden3_output = dL/dY_pred * dY_pred/dz_hidden3_output * dz_hidden3_output/db_hidden3_output
    # dL/dz_hidden3_output = dL/dY_pred * dY_pred/dz_hidden3_output
    # dL/db_hidden3_output = dL/dz_hidden3_output * dz_hidden3_output/db_hidden3_output

    dL_dz_hidden3_output = dL_dY_pred * dY_pred_dz_hidden3_output  # (1,1)
    dz_hidden3_output_db_hidden3_output = 1

    # dL/db_hidden3_output = dL/dz_hidden3_output * dz_hidden3_output/db_hidden3_output
    dL_db_hidden3_output = dL_dz_hidden3_output * dz_hidden3_output_db_hidden3_output # (1,1)



    # Hidden Layer 3 -> Hidden layer 2
    # ================================ WEIGHTS GRADIENTS ==============================================
    # dL/dw_hidden2_hidden3 = dL/da_hidden2_hidden3 * da_hidden2_hidden3/dz_hidden2_hidden3 * dz_hidden2_hidden3/dw_hidden2_hidden3
    # dL/da_hidden2_hidden3 = dL/dY_pred * dY_pred/dz_hidden3_output * dz_hidden3_output/da_hidden2_hidden3
    # da_hidden2_hidden3/dz_hidden2_hidden3 = a_hidden2_hidden3 * (1-a_hidden2_hidden3)
    # dz_hidden2_hidden3/dw_hidden2_hidden3 = a_hidden1_hidden2

    # dL/da_hidden2_hidden3 = dL/dY_pred * dY_pred/dz_hidden3_output * dz_hidden3_output/da_hidden2_hidden3
    # dL/dz_hidden3_output = dL/dY_pred * dY_pred/dz_hidden3_output

    dz_hidden3_output_da_hidden2_hidden3 = w_hidden3_output # (4,1)
    dL_da_hidden2_hidden3 = dL_dz_hidden3_output @ dz_hidden3_output_da_hidden2_hidden3.T # (1,4)

    # da_hidden2_hidden3/dz_hidden2_hidden3 = a_hidden2_hidden3 * (1-a_hidden2_hidden3)
    da_hidden2_hidden3_dz_hidden2_hidden3 = a_hidden2_hidden3 * (1-a_hidden2_hidden3) # (1,4)

    # dz_hidden2_hidden3/dw_hidden2_hidden3
    dz_hidden2_hidden3_dw_hidden2_hidden3 = a_hidden1_hidden2 # (1,8)

    # dL/dz_hidden2_hidden3 = dL/da_hidden2_hidden3 * da_hidden2_hidden3/dz_hidden2_hidden3
    dL_dz_hidden2_hidden3 = dL_da_hidden2_hidden3 * da_hidden2_hidden3_dz_hidden2_hidden3 # (1,4)

    # dL/dw_hidden2_hidden3 = dL/dz_hidden2_hidden3 * dz_hidden2_hidden3/dw_hidden2_hidden3
    dL_dw_hidden2_hidden3 = dz_hidden2_hidden3_dw_hidden2_hidden3.T @ dL_dz_hidden2_hidden3 # (8,4)


    # ================================ BIAS GRADIENTS ==============================================
    # dL/db_hidden2_hidden3  = dL/dz_hidden2_hidden3 * dz_hidden2_hidden3/db_hidden2_hidden3
    dz_hidden2_hidden3_db_hidden2_hidden3 = 1
    dL_db_hidden2_hidden3 = dL_dz_hidden2_hidden3 * dz_hidden2_hidden3_db_hidden2_hidden3 # (1,4)



    # Hidden Layer 2 -> Hidden Layer 1 
    # ================================ WEIGHTS GRADIENTS ==============================================
    # dL/dw_hidden1_hidden2 = dL/da_hidden1_hidden2 * da_hidden1_hidden2/dz_hidden1_hidden2 * dz_hidden1_hidden2/dw_hidden1_hidden2
    # dL/da_hidden1_hidden2 = dL/da_hidden2_hidden3 * da_hidden2_hidden3/dz_hidden2_hidden3 * dz_hidden2_hidden3/da_hidden1_hidden2
    # da_hidden1_hidden2/dz_hidden1_hidden2 = a_hidden1_hidden2 * (1-a_hidden1_hidden2)
    # dz_hidden1_hidden2/dw_hidden1_hidden2 = a_input_hidden1

    # dL/da_hidden1_hidden2 = dL/da_hidden2_hidden3 * da_hidden2_hidden3/dz_hidden2_hidden3 * dz_hidden2_hidden3/da_hidden1_hidden2
    # dL/dz_hidden2_hidden3 = dL/da_hidden2_hidden3 * da_hidden2_hidden3/dz_hidden2_hidden3

    dz_hidden2_hidden3_da_hidden1_hidden2 = w_hidden2_hidden3 # (8,4)
    dL_da_hidden1_hidden2  = dL_dz_hidden2_hidden3 @ dz_hidden2_hidden3_da_hidden1_hidden2.T # (1,8)

    # da_hidden1_hidden2/dz_hidden1_hidden2 = a_hidden1_hidden2 * (1-a_hidden1_hidden2)
    da_hidden1_hidden2_dz_hidden1_hidden2 = a_hidden1_hidden2 * (1-a_hidden1_hidden2)  # (1,8)

    # dz_hidden1_hidden2/dw_hidden1_hidden2 = a_input_hidden1
    dz_hidden1_hidden2_dw_hidden1_hidden2 = a_input_hidden1 # (1,16)

    # dL/dz_hidden1_hidden2 = dL/da_hidden1_hidden2 * da_hidden1_hidden2/dz_hidden1_hidden2
    dL_dz_hidden1_hidden2 = dL_da_hidden1_hidden2 * da_hidden1_hidden2_dz_hidden1_hidden2 # (1,8)

    # dL/dw_hidden1_hidden2 = dL/da_hidden1_hidden2 * da_hidden1_hidden2/dz_hidden1_hidden2 * dz_hidden1_hidden2/dw_hidden1_hidden2
    dL_dw_hidden1_hidden2 = dz_hidden1_hidden2_dw_hidden1_hidden2.T @ dL_dz_hidden1_hidden2 # (16,8)


    # ================================ BIAS GRADIENTS ==============================================
    # dL/db_hidden1_hidden2 = dL/dz_hidden1_hidden2 * dz_hidden1_hidden2/db_hidden1_hidden2
    dz_hidden1_hidden2_db_hidden1_hidden2 = 1
    dL_db_hidden1_hidden2 = dL_dz_hidden1_hidden2 * dz_hidden1_hidden2_db_hidden1_hidden2 # (1,8)



    # Hidden Layer 1 -> Input Layer 
    # ================================ WEIGHTS GRADIENTS ===========================================
    # dL/dw_input_hidden1 = dL/da_input_hidden1 * da_input_hidden1/dz_input_hidden1 * dz_input_hidden1/dw_input_hidden1
    # dL/da_input_hidden1 = dL/da_hidden1_hidde2 * da_hidden1_hidden2/dz_hidden1_hidden2 * dz_hidden1_hidden2/da_input_hidden1
    # da_input_hidden1/dz_input_hidden1 = a_input_hidden1 * (1 - a_input_hidden1)
    # dz_input_hidden1/dw_input_hidden1 = X

    # dL/da_input_hidden1 = dL/da_hidden1_hidde2 * da_hidden1_hidden2/dz_hidden1_hidden2 * dz_hidden1_hidden2/da_input_hidden1
    # dL/dz_hidden1_hidden2 = dL/da_hidden1_hidde2 * da_hidden1_hidden2/dz_hidden1_hidden2 # (1,8)
    dz_hidden1_hidden2_da_input_hidden1 = w_hidden1_hidden2 # (16,8)
    dL_da_input_hidden1 = dL_dz_hidden1_hidden2 @ dz_hidden1_hidden2_da_input_hidden1.T # (1,16)

    # da_input_hidden1/dz_input_hidden1 = a_input_hidden1 * (1 - a_input_hidden1)
    da_input_hidden1_dz_input_hidden1 = a_input_hidden1 * (1-a_input_hidden1) # (1,16)

    # dL/dz_input_hidden1 = dL/da_input_hidden1 * da_input_hidden1/dz_input_hidden1
    dL_dz_input_hidden1 = dL_da_input_hidden1 * da_input_hidden1_dz_input_hidden1 # (1,16)

    # dz_input_hidden1/dw_input_hidden1 = X
    dz_input_hidden1_dw_input_hidden1 = X # (1,1)

    # dL/dw_input_hidden1 = dL/dz_input_hidden1 * dz_input_hidden1/dw_input_hidden1
    dL_dw_input_hidden1 = dz_input_hidden1_dw_input_hidden1 @ dL_dz_input_hidden1 # (1,16)


    # ================================ BIAS GRADIENTS ==============================================
    # dL/db_input_hidden1 = dL/dz_input_hidden1 * dz_input_hidden1/db_input_hidden1
    # dz_input_hidden1/db_input_hidden1 = 1
    dz_input_hidden1_db_input_hidden1 = 1
    dL_db_input_hidden1 = dL_dz_input_hidden1 * dz_input_hidden1_db_input_hidden1 # (1,16)



    # ==================================== WEIGHTS, BIAS UPDATION ========================================
    # Output Layer -> Hidden Layer 3
    w_hidden3_output -= LR*dL_dw_hidden3_output
    b_hidden3_output -= LR*dL_db_hidden3_output

    # Hidden Layer 3 -> Hidden Layer 2
    w_hidden2_hidden3 -= LR*dL_dw_hidden2_hidden3
    b_hidden2_hidden3 -= LR*dL_db_hidden2_hidden3

    # Hidden Layer 2 -> Hidden Layer 1
    w_hidden1_hidden2 -= LR*dL_dw_hidden1_hidden2
    b_hidden1_hidden2 -= LR*dL_db_hidden1_hidden2

    # Hidden Layer 1 -> Input Layer
    w_input_hidden1 -= LR*dL_dw_input_hidden1
    b_input_hidden1 -= LR*dL_db_input_hidden1


    if (epoch+1) %100 == 0:
        print(
            f"Epoch : {epoch+1}| Loss : {L.item():.6f} | Y_pred : {Y_pred.item():.6f}")



Epoch : 100| Loss : 0.066495 | Y_pred : 0.635321
Epoch : 200| Loss : 0.054968 | Y_pred : 0.668434
Epoch : 300| Loss : 0.046045 | Y_pred : 0.696537
Epoch : 400| Loss : 0.039079 | Y_pred : 0.720433
Epoch : 500| Loss : 0.033579 | Y_pred : 0.740850
Epoch : 600| Loss : 0.029184 | Y_pred : 0.758404
Epoch : 700| Loss : 0.025628 | Y_pred : 0.773603
Epoch : 800| Loss : 0.022715 | Y_pred : 0.786857
Epoch : 900| Loss : 0.020302 | Y_pred : 0.798496
Epoch : 1000| Loss : 0.018281 | Y_pred : 0.808787
Epoch : 1100| Loss : 0.016572 | Y_pred : 0.817943
Epoch : 1200| Loss : 0.015114 | Y_pred : 0.826137
Epoch : 1300| Loss : 0.013859 | Y_pred : 0.833511
Epoch : 1400| Loss : 0.012771 | Y_pred : 0.840180
Epoch : 1500| Loss : 0.011821 | Y_pred : 0.846242
Epoch : 1600| Loss : 0.010985 | Y_pred : 0.851774
Epoch : 1700| Loss : 0.010247 | Y_pred : 0.856845
Epoch : 1800| Loss : 0.009590 | Y_pred : 0.861509
Epoch : 1900| Loss : 0.009003 | Y_pred : 0.865815
Epoch : 2000| Loss : 0.008476 | Y_pred : 0.869802
Epoch : 2